version: '3'
services:
  db:
    image: mariadb:10
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=cypht
      - MYSQL_USER=cypht
      - MYSQL_PASSWORD=cypht_password
  cypht:
    # image: sailfrog/cypht-docker:latest
    # image: jonocodes/cypht:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./data/users:/var/lib/hm3/users
      - ./data/attachments:/var/lib/hm3/attachments
      - ./data/app_data:/var/lib/hm3/app_data
      - ./:/usr/local/share/cypht # allows live develompent in container
    ports:
      - "80:80"
    environment:
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=admin
      # - DB_CONNECTION_TYPE=socket
      # - DB_DRIVER=sqlite
      # - DB_SOCKET=/tmp/cypht_1.sqlite # TODO: move to ./db ?
      - DB_CONNECTION_TYPE=host
      - DB_HOST=db
      - DB_NAME=cypht
      - DB_USER=cypht
      - DB_PASS=cypht_password
      - DB_DRIVER=mysql
      - SESSION_TYPE=DB
      - USER_CONFIG_TYPE=DB


  # TODO: add memcache and redis to this sample, or disable it via env vars
